# Generated by Django 4.1.3 on 2022-12-05 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appclase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='fecha_nacimineto',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 12, 5, 13, 57, 53, 950045, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
    ]
